stages:
  - build
  - release

build-gradle-project:
  stage: build
  script:
    - ./gradlew :build --stacktrace
  variables:
    QUARKUS_CONTAINER_IMAGE_IMAGE: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID

push-to-registry:
  stage: release
  script:
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
